name: Fetch BLS Data Monthly

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:   

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install streamlit==1.40.1
          pip install matplotlib pandas requests schedule

      - name: Ensure 'data' directory exists
        run: |
          mkdir -p data

      - name: Run BLS data fetch script
        run: |
          python semester_project_.py 

      - name: Commit and push new data
        run: |
          git add data/bls_data.csv
          git commit -m "Update BLS data"
          git push
