name: Automate BLS Data Fetch

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:
  
jobs:
  run-bls-data-fetch:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (if you have a requirements.txt)
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the Python script
      - name: Run Python script
        run: |
          python semester_project_.py

      # Step 5: Commit and push the generated CSV file back to the repository
      - name: Commit and push CSV file
        run: |
          # Set up git user
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Add the CSV file
          git add data/bls_data.csv

          # Commit the changes
          git commit -m "Update bls_data.csv with new data"

          # Push the changes to the repository
          git push origin main  # Make sure you're pushing to the correct branch
        env:
          # GitHub Actions automatically provides a token to authenticate Git operations
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
